install:
  - cmd: npm install && npm install git://github.com/select2/select2
    input: package.json
    output: node_modules

build:
  - gulp

purge:
  - assets
  - lib
  - node_modules
  - composer.json
  - test
  - "*.md"
  - ".*"
  - "*.json"
  - gulpfile.js
